version: '3.8'

services:
  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model-deployment-backend
    ports:
      - "8000:8000"    # Main API
      - "8001-8010:8001-8010"  # Model servers
    volumes:
      - ./deployed_models:/app/deployed_models
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - DEFAULT_WORKERS=4
      - DEFAULT_PORT_START=8001
    restart: unless-stopped
    networks:
      - model-deployment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Frontend (if you want to run it in Docker too)
  # Uncomment if you want to containerize the frontend
  # frontend:
  #   image: node:18-alpine
  #   container_name: model-deployment-frontend
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   command: sh -c "npm install && npm run dev -- --host"
  #   depends_on:
  #     - backend
  #   networks:
  #     - model-deployment-network

networks:
  model-deployment-network:
    driver: bridge

volumes:
  deployed_models:
  uploads:
  logs:
